version: '3.9'

services:
  postgres:
    image: postgres:12.3-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: pg_db
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:4.23
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
     - postgres
  flask:
    build: .
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SECRET_KEY="YOUR SECRET KEY HERE"
volumes:
  postgres:
  pgadmin: